version: '3'
services:
  api:
    build: .
    command: nodemon node run dev
    ports:
      - "5000:5000"
    volumes: 
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  